output_dir = "./runs/test_d_concat"
logging_dir = "./runs"
experiment_name = "test_d_concat"
checkpointing_steps = 8
# log_level = "DEBUG"

accelerator_amp_mode = "no"
base_precision = "fp8-upcast"
trainable_precision = "bf16"
allow_tf32 = true
gradient_checkpointing = true
use_8bit_adam = false

seed = 42
gradient_accumulation_steps = 2
train_steps = 32
lr_scheduler = "constant"
weighting_scheme = "logit_normal"

[dataset]
type = "mock"
num_samples = 16

[adapter]
type = "d_concat"