output_dir = "./runs/test_collage_v2"
logging_dir = "./runs"
experiment_name = "test_collage_v2"
checkpointing_steps = 10
sample_steps = 10
# sample_pickle_dir = "data/sample_v2"

accelerator_amp_mode = "no"
base_precision = "fp8-upcast"
trainable_precision = "bf16"
allow_tf32 = true
gradient_checkpointing = true
use_8bit_adam = false

seed = 42
gradient_accumulation_steps = 2
train_steps = 20
learning_rate = 5e-6
lr_scheduler = "constant"
weighting_scheme = "logit_normal"

[dataset]
type = "mock_collage_v2"

[adapter]
type = "collage_v2"
rank = 128

[sampler]
seed = 42
infer_size_from = "confidence"
infer_size_ratio = 16
steps = 5